---
- hosts: test-server
  become: true
  tasks:
  - name: update apt
    command: sudo apt-get update

  - name: install docker
    command: sudo apt install -y docker.io

  - name: start docker service
    command: sudo systemctl start docker

  - name: stop all docker contianer
    command: sudo docker stop $(docker ps -a -q)
   
  - name: remove all the container
    command: sudo docker rm $(docker ps -a -q)
    
  - name: deploy insureme application
    command: sudo docker run -itd -p 8081:8081 --name insure-me tekbista37545/insure-me:1.0
